gity/java-fx: fix missing main class
This one is easy: let's use the class explicitly rather than relying on
reflection to find it.

Next error:

```
$ ./minimaljavafxapp
java.lang.ClassNotFoundException: com.sun.javafx.tk.quantum.QuantumToolkit
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:215)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:183)
        at java.base@24.0.1/java.lang.Class.forName(DynamicHub.java:1509)
        at java.base@24.0.1/java.lang.Class.forName(DynamicHub.java:1497)
        at javafx.graphics@24.0.1/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:241)
        at javafx.graphics@24.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:274)
        at javafx.graphics@24.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:154)
        at javafx.graphics@24.0.1/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:652)
        at javafx.graphics@24.0.1/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:672)
        at javafx.graphics@24.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$0(LauncherImpl.java:197)
        at java.base@24.0.1/java.lang.Thread.runWith(Thread.java:1460)
        at java.base@24.0.1/java.lang.Thread.run(Thread.java:1447)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at javafx.graphics@24.0.1/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:263)
        at javafx.graphics@24.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:274)
        at javafx.graphics@24.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:154)
        at javafx.graphics@24.0.1/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:652)
        at javafx.graphics@24.0.1/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:672)
        at javafx.graphics@24.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$0(LauncherImpl.java:197)
        at java.base@24.0.1/java.lang.Thread.runWith(Thread.java:1460)
        at java.base@24.0.1/java.lang.Thread.run(Thread.java:1447)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
$
```